# Licensed under the terms of http://www.apache.org/licenses/LICENSE-2.0

## Fuseki Server authentication and authorization configuration

[main]
# Development
ssl.enabled = false

[users]
# username = password
admin=admin

[urls]
## Control functions open to anyone
/$/ping = anon
/$/stats = anon
/$/metrics = anon
/$/server = anon

## Allow access to the Fuseki UI
/ = anon

## Allow full access for development
## IMPORTANT: For production, replace 'anon' with 'authcBasic,user[admin]'
/**=anon
